# Date format
date:
  format: "dd-MM-yyyy HH:mm:ss"
  timezone: "UTC"

# Taps configuration
taps:
  file:
    path: "src/main/resources/taps.csv"
  headers: "ID,DateTimeUTC,TapType,StopId,CompanyId,BusID,PAN"

# Trips configuration
trips:
  file:
    path: "target/trips.csv"
  headers: "Started,Finished,DurationSecs,FromStopId,ToStopId,ChargeAmount,CompanyId,BusID,PAN,Status"

# Fare mapping
fare:
  mapping:
    - from: Stop1
      to: Stop2
      cost: 3.25
    - from: Stop2
      to: Stop3
      cost: 5.50
    - from: Stop1
      to: Stop3
      cost: 7.30